routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ArticleController@index');

Route::get('details-choco/{id}', 'ArticleController@show');

Route::get('/home', function () {
    return view('home');
});

Route::get('/mes_reservations', function () {
    return view('mes_reservations');
});

Route::get('/chocolats', 'ArticleController@seeAllChocolats');

Route:: get('/a_propos', function () {
    return view('a_propos');
});

Route::get('/reservation', function () {
    return view('reservation/cart');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// VOIR TOUT LES PRODUITS EN TANT QU'ADMIN (CRUD)
Route::get('/index', 'ArticleController@index2');

Route::resource('admin', 'ArticleController');

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card uper">
  <div class="card-header">
    Ajouter un Produit !
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('admin.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nom du Produit :</label>
              <input type="text" class="form-control" name="name" id="name"/>
          </div>
          <div class="form-group">
              <label for="description">Description :</label>
              <input type="text" class="form-control" name="description" id="description"/>
          </div>
          <div class="form-group">
              <label for="image">Url de l'image du produit :</label>
              <input type="text" class="form-control" name="image" id="image"/>
          </div>
          <div class="form-group">
              <label for="unit_price">Prix a l'unité (en euros) :</label>
              <input type="number" class="form-control" name="price" id="price"/>
          </div>
          <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card uper">
  <div class="card-header">
    Modifier le produit
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('admin.update', $article->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Nom du produit:</label>
          <input type="text" class="form-control" name="name" value={{ $article->name }} />
        </div>
        <div class="form-group">
          <label for="price">Description du produit :</label>
          <input type="text" class="form-control" name="description" value={{ $article->description }} />
        </div>
        <div class="form-group">
          <label for="price">Url de l'image :</label>
          <input type="text" class="form-control" name="image" value={{ $article->image }} />
        </div>
        <div class="form-group">
          <label for="price">Prix a l'unité :</label>
          <input type="text" class="form-control" name="price" value={{ $article->price }} />
        </div>
        <button type="submit" class="btn btn-primary">Mettre à jour</button>
      </form>
  </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
<div>
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr class="text-center">
          <td>ID</td>
          <td>Nom du Produit</td>
          <td>Prix a l'unité</td>
          <td>Description</td>
          <td>Photo</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
    @foreach($articles as $article)
        <tr class="text-center">
            <td>{{ $article->id }}</td>
            <td>{{ $article->name }}</td>
            <td>{{ $article->price }}</td>
            <td>{{ $article->description }}</td>
            <td><img src="{{url($article->image)}}" alt=""></td>
            <td><a href="{{ route('admin.edit',$article->id)}}" class="btn btn-primary">Modifier</a></td>
            <td>
                <form action="{{ route('admin.destroy', $article->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Supprimer</button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
  </table>
<div>

<a href="{{ route('admin.create') }}" class="btn btn-primary btn-lg btn-block">AJOUTER UN PRODUIT</a>
@endsection